import './globals.css';
import { Inter } from 'next/font/google';

import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });
const styles = "font-nunito";

export const metadata = {
  title: 'My Component Laboratory',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div id="wrapper-div" className={inter.className + " " + styles}>
          <div id="content" className="">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
